steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'scp', '--recurse', '--zone=<your_vm_zone>', 'new_index.html', '<your_vm_name>:<path_to_htdocs>']
options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: masumtest
